module.exports.id=module.id;
var changeLog = [
    { changeID:"dir_retail_receipt_purposes__1", changeDatetime:"2017-06-26 16:21:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"CREATE TABLE dir_retail_receipt_purposes(ID INTEGER NOT NULL PRIMARY KEY) CHARACTER SET utf8",
        tableName:"dir_retail_receipt_purposes", field:"ID"},
    { changeID:"dir_retail_receipt_purposes__2", changeDatetime:"2017-06-26 16:22:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"ALTER TABLE dir_retail_receipt_purposes ADD COLUMN VALUE VARCHAR(255) NOT NULL",
        field:"VALUE"},
    { changeID:"dir_retail_receipt_purposes__3", changeDatetime:"2017-06-26 16:23:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"ALTER TABLE dir_retail_receipt_purposes ADD CONSTRAINT DIR_RETAIL_RECEIPT_PURPOSES_VALUE_UNIQUE " +
            "UNIQUE(VALUE)"},
    { changeID:"dir_retail_receipt_purposes__4", changeDatetime:"2017-06-26 16:24:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"ALTER TABLE dir_retail_receipt_purposes ADD COLUMN FOR_CASHIN SMALLINT UNSIGNED NOT NULL",
        field:"FOR_CASHIN"},
    { changeID:"dir_retail_receipt_purposes__5", changeDatetime:"2017-06-26 16:25:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"ALTER TABLE dir_retail_receipt_purposes ADD COLUMN FOR_CASHOUT SMALLINT UNSIGNED NOT NULL",
        field:"FOR_CASHOUT"},
    { changeID:"dir_retail_receipt_purposes__6", changeDatetime:"2017-06-26 16:41:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"INSERT INTO dir_retail_receipt_purposes(ID,VALUE,FOR_CASHIN,FOR_CASHOUT) values(1,'Размен.монета',1,0)"},
    //{ changeID:"dir_retail_receipt_purposes__7", changeDatetime:"2017-06-26 16:42:00", changeObj:"dir_retail_receipt_purposes",
    //    changeVal:"INSERT INTO dir_retail_receipt_purposes(ID,VALUE,FOR_CASHIN,FOR_CASHOUT) values(2,'Для выдачи З/П',1,0)"},
    { changeID:"dir_retail_receipt_purposes__8", changeDatetime:"2017-06-26 16:43:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"INSERT INTO dir_retail_receipt_purposes(ID,VALUE,FOR_CASHIN,FOR_CASHOUT) values(-1,'Инкассация',0,1)"},
    { changeID:"dir_retail_receipt_purposes__9", changeDatetime:"2017-06-26 16:44:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"INSERT INTO dir_retail_receipt_purposes(ID,VALUE,FOR_CASHIN,FOR_CASHOUT) values(-2,'З/П аванс',0,1)"},
    { changeID:"dir_retail_receipt_purposes_10", changeDatetime:"2017-06-26 16:45:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"INSERT INTO dir_retail_receipt_purposes(ID,VALUE,FOR_CASHIN,FOR_CASHOUT) values(-3,'З/П',0,1)"},
    { changeID:"dir_retail_receipt_purposes_11", changeDatetime:"2017-06-26 16:46:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"INSERT INTO dir_retail_receipt_purposes(ID,VALUE,FOR_CASHIN,FOR_CASHOUT) values(-4,'Чай/кофе/сахар',0,1)"},
    { changeID:"dir_retail_receipt_purposes_12", changeDatetime:"2017-06-26 16:47:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"INSERT INTO dir_retail_receipt_purposes(ID,VALUE,FOR_CASHIN,FOR_CASHOUT) values(-5,'Моющие',0,1)"},
    { changeID:"dir_retail_receipt_purposes_13", changeDatetime:"2017-06-26 16:48:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"INSERT INTO dir_retail_receipt_purposes(ID,VALUE,FOR_CASHIN,FOR_CASHOUT) values(-6,'Транспортные расх.',0,1)"},
    { changeID:"dir_retail_receipt_purposes_14", changeDatetime:"2017-06-26 16:49:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"INSERT INTO dir_retail_receipt_purposes(ID,VALUE,FOR_CASHIN,FOR_CASHOUT) values(-7,'Оплата водителю',0,1)"},
    { changeID:"dir_retail_receipt_purposes_15", changeDatetime:"2017-06-26 16:50:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"INSERT INTO dir_retail_receipt_purposes(ID,VALUE,FOR_CASHIN,FOR_CASHOUT) values(-8,'Рекламные расходы',0,1)"},
    { changeID:"dir_retail_receipt_purposes_16", changeDatetime:"2017-06-26 16:51:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"INSERT INTO dir_retail_receipt_purposes(ID,VALUE,FOR_CASHIN,FOR_CASHOUT) values(-9,'День рожденья',0,1)"},
    { changeID:"dir_retail_receipt_purposes_17", changeDatetime:"2017-06-26 16:52:00", changeObj:"dir_retail_receipt_purposes",
        changeVal:"INSERT INTO dir_retail_receipt_purposes(ID,VALUE,FOR_CASHIN,FOR_CASHOUT) values(-10,'Празничная премия',0,1)"}
    //{ changeID:"dir_retail_receipt_purposes_18", changeDatetime:"2017-06-26 16:53:00", changeObj:"dir_retail_receipt_purposes",
    //    changeVal:"INSERT INTO dir_retail_receipt_purposes(ID,VALUE,FOR_CASHIN,FOR_CASHOUT) values(-11,'Прочие расходы',0,1)"}
];
module.exports.changeLog=changeLog;
