var changeLog = [
{ 'changeID':'sys_sync_errors_log__1', 'changeDatetime':'2016-11-26T14:01:00.000+0200', 'changeObj':'model.sys_sync_errors_log',
    'changeVal':'CREATE TABLE sys_sync_errors_log(ID BIGINT NOT NULL PRIMARY KEY) CHARACTER SET utf8',
    "tableName":"sys_sync_errors_log", "field":"ID"},
{ 'changeID':'sys_sync_errors_log__2', 'changeDatetime':'2016-11-26T14:02:00.000+0200', 'changeObj':'model.sys_sync_errors_log',
    'changeVal':'ALTER TABLE sys_sync_errors_log ADD COLUMN ERROR_MSG VARCHAR(1024) NOT NULL',
    "field":"ERROR_MSG"},
{ 'changeID':'sys_sync_errors_log__3', 'changeDatetime':'2016-11-26T14:03:00.000+0200', 'changeObj':'model.sys_sync_errors_log',
    'changeVal':'ALTER TABLE sys_sync_errors_log ADD COLUMN CREATE_DATE TIMESTAMP NOT NULL',
    "field":"CREATE_DATE"},
{ 'changeID':'sys_sync_errors_log__4', 'changeDatetime':'2016-11-26T14:04:00.000+0200', 'changeObj':'model.sys_sync_errors_log',
    'changeVal':'ALTER TABLE sys_sync_errors_log ALTER COLUMN CREATE_DATE  DROP DEFAULT' },
{ 'changeID':'sys_sync_errors_log__5', 'changeDatetime':'2016-11-26T14:05:00.000+0200', 'changeObj':'model.sys_sync_errors_log',
    'changeVal':'ALTER TABLE sys_sync_errors_log ADD COLUMN HEADER VARCHAR(255)',
    "field":"HEADER"},
{ 'changeID':'sys_sync_errors_log__6', 'changeDatetime':'2016-11-26T14:06:00.000+0200', 'changeObj':'model.sys_sync_errors_log',
    'changeVal':'ALTER TABLE sys_sync_errors_log ADD COLUMN CLIENT_DB_NAME VARCHAR(255)',
    "field":"CLIENT_DB_NAME"},
{ 'changeID':'sys_sync_errors_log__7', 'changeDatetime':'2016-11-26T14:07:00.000+0200', 'changeObj':'model.sys_sync_errors_log',
    'changeVal':'ALTER TABLE sys_sync_errors_log ADD COLUMN CLIENT_POS_NAME VARCHAR(255)',
    "field":"CLIENT_POS_NAME"},
{ 'changeID':'sys_sync_errors_log__8', 'changeDatetime':'2016-11-26T14:08:00.000+0200', 'changeObj':'model.sys_sync_errors_log',
    'changeVal':'ALTER TABLE sys_sync_errors_log ADD COLUMN CLIENT_STOCK_NAME VARCHAR(255)',
    "field":"CLIENT_STOCK_NAME"},
{ 'changeID':'sys_sync_errors_log__9', 'changeDatetime':'2016-11-26T14:09:00.000+0200', 'changeObj':'model.sys_sync_errors_log',
    'changeVal':'ALTER TABLE sys_sync_errors_log ADD COLUMN CLIENT_CREATE_DATE TIMESTAMP NULL',
    "field":"CLIENT_CREATE_DATE"},
{ 'changeID':'sys_sync_errors_log_10', 'changeDatetime':'2016-11-26T14:10:00.000+0200', 'changeObj':'model.sys_sync_errors_log',
    'changeVal':'ALTER TABLE sys_sync_errors_log ALTER COLUMN CLIENT_CREATE_DATE  DROP DEFAULT' },
{ 'changeID':'sys_sync_errors_log_11', 'changeDatetime':'2016-11-26T14:11:00.000+0200', 'changeObj':'model.sys_sync_errors_log',
    'changeVal':'ALTER TABLE sys_sync_errors_log ADD COLUMN CLIENT_SYNC_DATA_ID VARCHAR(255)',
    "field":"CLIENT_SYNC_DATA_ID"}
];
module.exports.changeLog=changeLog;